/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Schema {
  paths: {
    vim: string;
    [k: string]: unknown | undefined;
  };
  github?: {
    token: string;
    username: string;
    gist?: string;
    [k: string]: unknown | undefined;
  };
  [k: string]: unknown | undefined;
}
